version: '3.8'

services:
  backend:
    build:
      context: ${BACKEND_PATH}
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

  db:
    image: postgres:15.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=playwright
      - POSTGRES_USER=playwright
      - POSTGRES_PASSWORD=Playwright1234
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U playwright']
      interval: 5s
      timeout: 5s
      retries: 5
